server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    include: oauth, local

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


cors:
  enabled: true
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: authorization,content-type,x-auth-token
  max-age: 3600

app:
  auth:
    token-secret: 926D96C90030DD58429D2751AC1BDBBC
    token-expiry: 9000000
    refresh-token-expiry: 604800000
  oauth2:
    authorized-redirect-uris: http://localhost:3000/kakao
logging.level:
  org.hibernate.SQL: debug
  org:
    springframework: info
# org.hibernate.type: trace
