spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: X
            client-secret: X
            redirect-uri: http://localhost:9285/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver


          kakao:
            client-id: 186db3a276355426492e41a502011b88
            redirect-uri: https://localhost:9090/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: n9EZSS2eagtrsOO1U5kR2YuO1XZUgk62
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client_name: kakao


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'


KAKAO_CLIENT_ID: '186db3a276355426492e41a502011b88'
KAKAO_CLIENT_SECRET: 'n9EZSS2eagtrsOO1U5kR2YuO1XZUgk62'
