server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    include: local

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secretKey: "d21b5b9c6ee776cac626c60a1d113ee43e9055c04f17cafb37bcfb4b128e01fe2566a1b7c159343279cab64b375ed3eee848b7a2efb65f17325a1f15f50bc5d10427108b5452bf8ca62cdb7ab1ce7c69713746c26121760be8eac9f231258b473416640dd60d68a591ddec2ce55bc1a4fe65332aedf45ab9ce2dd0d0a3c358d9"
  algorithm: "HS256"
cors:
  allowed-origins: http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: authorization,content-type,x-auth-token
  max-age: 3600

app:
  auth:
    token-secret: 926D96C90030DD58429D2751AC1BDBBC
    token-expiry: 1800000
    refresh-token-expiry: 604800000
  oauth2:
    authorized-redirect-uris: http://localhost:8080/oauth/redirect
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace