spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/farmcu?serverTimezone=Asia/Seoul
#    username: ssafy
#    password: ssafy

    # 지은 - 임시 사용
    url: jdbc:mysql://localhost:3306/fcmus?serverTimezone=Asia/Seoul
    username: root
    password: ssafyB10312345

# swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 186db3a276355426492e41a502011b88
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: n9EZSS2eagtrsOO1U5kR2YuO1XZUgk62
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client_name: kakao


          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 112610492279-v01g2d5juv2bvd9d42q4b19ii168q36h.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
    secretKey: "359568ca4a6d006075e777936278ab4ce4a143ab4f74aa963e5df676a5f85c2d73f2b7cd75e74eab8f60781b7942cfe030c39a29e69521907c2fd53fcac7036b"
    algorithm: "HS256"

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace